//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Data.DataClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KPContext : DbContext
    {
        public KPContext()
            : base("name=KPContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<const_rekv> const_rekv { get; set; }
        public virtual DbSet<constlist_rekv> constlist_rekv { get; set; }
        public virtual DbSet<dynamic_rekv> dynamic_rekv { get; set; }
        public virtual DbSet<objects> objects { get; set; }
        public virtual DbSet<ASysStoreItems> ASysStoreItems { get; set; }
        public virtual DbSet<JRN_Orders> JRN_Orders { get; set; }
        public virtual DbSet<REC_View_StoreItem> REC_View_StoreItem { get; set; }
        public virtual DbSet<REF> REF { get; set; }
        public virtual DbSet<JRN_Orders_Records> JRN_Orders_Records { get; set; }
    }
}
