//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Data.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class JRN_Orders_Records
    {
        public int id { get; set; }
        public Nullable<int> id_order { get; set; }
        public string PartName { get; set; }
    }
}
