//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Data.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class dynamic_rekv
    {
        public int id { get; set; }
        public Nullable<int> object_id { get; set; }
        public Nullable<int> ID_AppObjRekv { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public string charval { get; set; }
        public Nullable<bool> boolval { get; set; }
        public Nullable<System.DateTime> dateval { get; set; }
        public Nullable<double> floatval { get; set; }
        public Nullable<int> intval { get; set; }
        public Nullable<int> id_tran { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<int> intval2 { get; set; }
    }
}
