//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Data.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class JRN_Orders
    {
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<int> id_OrderType { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public Nullable<System.DateTime> date_archive { get; set; }
        public string Note { get; set; }
        public Nullable<int> id_folder { get; set; }
        public int status { get; set; }
        public Nullable<int> id_tran { get; set; }
        public Nullable<int> id_firm { get; set; }
        public string cmd_params { get; set; }
        public Nullable<int> id_replaced { get; set; }
        public Nullable<int> id_replacing { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string additional_params { get; set; }
        public string LastModifiedUser { get; set; }
        public string ObjName { get; set; }
    }
}
