//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Data.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF
    {
        public int ID { get; set; }
        public string ObjName { get; set; }
        public string Code { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string StructureCode { get; set; }
        public bool brief { get; set; }
        public Nullable<int> id_folder { get; set; }
        public string SystemCode { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Cod { get; set; }
        public Nullable<int> ID_Rekv { get; set; }
        public string RelevanceCode { get; set; }
    }
}
